<?php

require_once DRUPAL_ROOT . '/sites/all/modules/custom/zendesk_events/zendesk_api_client/vendor/autoload.php';

use Zendesk\API\HttpClient as ZendeskAPI;

$subdomain = "acquia1457030485";
$username  = "blake.scott@acquia.com"; // replace this with your registered email
$token     = "xlHUq4xOk4KI8IjBUWHw0CIwq7MeXPx3KFCACw8m"; // replace this with your token

$client = new ZendeskAPI($subdomain);
$client->setAuth('basic', ['username' => $username, 'token' => $token]);

$fake_calendar_org_ids = array(14114387868, 27811797827);

// Return all tickets from our custom view.
$tickets = $client->views(360049656394)->tickets();
//Grab the org ids from each ticket, and put them in an array.
$ticket_orgs = array_column($tickets->tickets, 'organization_id');
//find org id matches, if any
$matching_org_ids = array_intersect($ticket_orgs, $fake_calendar_org_ids);

//print ticket org id array, then print org ids that match the fake calendar org ids
print_r($ticket_orgs);
print_r(' . . . . .');
print_r($matching_org_ids);




/* add a comment (this doesn't work yet)

$add_comment = $client->views(360049656394)->tickets()->create([
    'comment' => [
        'body' => 'Blake added a comment',
    ]
]); */
